CREATE DATABASE IF NOT EXISTS auth;
USE auth;

CREATE TABLE IF NOT EXISTS users(
	id CHAR(38) NOT NULL DEFAULT (uuid()),
	name VARCHAR(150) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(200),
	create_at BIGINT
);